### ISSUE TITLE
looking for documents, but the website was dead maybe.

### ISSUE THREAD

**Issue by eotect** [johnsonyl/cpps#1]
看了更新日记，作者好勤奋~，除此之外，感觉这个脚本解释器也太强大了。
特别想试用一下，但找不到文档。
不知能不能把文档放到github里面，或者就包含在项目里面。
感谢分享。

**Comment by johnsonyl** [comment]
https://github.com/johnsonyl/cpps/blob/master/CPPS_document_100.md
